#!/usr/bin/env python3
"""Embed the DTBO and record only external phandle property offsets."""
import struct
import sys
from pathlib import Path


def embed(source, target):
    blob = Path(source).read_bytes()
    magic, size, start, strings = struct.unpack_from(">4I", blob)
    if magic != 0xD00DFEED or size != len(blob):
        raise ValueError("invalid DTBO header")
    offsets = {0xFEED0001: [], 0xFEED0002: [], 0xFEED0003: []}
    nodes = []
    pos = start
    while True:
        token = struct.unpack_from(">I", blob, pos)[0]
        pos += 4
        if token == 1:  # FDT_BEGIN_NODE
            nodes.append(blob[pos:blob.index(b"\0", pos)])
            pos = (blob.index(b"\0", pos) + 4) & ~3
        elif token == 3:  # FDT_PROP
            length, nameoff = struct.unpack_from(">2I", blob, pos)
            pos += 8
            name = blob[strings + nameoff:blob.index(b"\0", strings + nameoff)]
            if name in (b"interrupt-parent", b"power-domains"):
                for off in range(pos, pos + length, 4):
                    value = struct.unpack_from(">I", blob, off)[0]
                    if value in offsets:
                        offsets[value].append(off)
            pos += (length + 3) & ~3
        elif token == 9:  # FDT_END
            break
        elif token not in (2, 4):
            raise ValueError(f"invalid FDT token {token}")
    if [len(v) for v in offsets.values()] != [2, 1, 1]:
        raise ValueError(f"unexpected external phandle locations: {offsets}")
    if b"__symbols__" in nodes or b"__fixups__" in nodes:
        raise ValueError("runtime overlay must not depend on a live symbol table")
    if b"__local_fixups__" not in nodes:
        raise ValueError("runtime overlay is missing internal phandle fixups")
    lines = ["/* Generated by embed-overlay.py; do not edit. */",
             "static const unsigned char ane_overlay[] = {"]
    for off in range(0, len(blob), 16):
        lines.append("\t" + ", ".join(f"0x{b:02x}" for b in blob[off:off+16]) + ",")
    lines.append("};")
    for name, values in zip(("aic", "sys", "cpu"), offsets.values()):
        lines.append(f"static const unsigned int {name}_offsets[] = {{" +
                     ", ".join(map(str, values)) + "};")
    Path(target).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    embed(*sys.argv[1:])
